"""add farmer address wallet balance

Revision ID: 9c3e39b16d38
Revises: da29916875ec
Create Date: 2023-03-05 22:58:20.068682

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '9c3e39b16d38'
down_revision = 'da29916875ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_target_wallet_balance_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmer_target_wallet_balance_events'))
    )
    op.create_index(op.f('ix_farmer_target_wallet_balance_events_ts'), 'farmer_target_wallet_balance_events', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmer_target_wallet_balance_events_ts'), table_name='farmer_target_wallet_balance_events')
    op.drop_table('farmer_target_wallet_balance_events')
    # ### end Alembic commands ###
